version: '3.8'

services:
  web:
    image: my-php-app
    container_name: my-php-app
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db
    networks:
      - my-network

  db:
    image: mysql:8.0
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: lord139055
      MYSQL_DATABASE: my_database
    ports:
      - "3306:3306"
    networks:
      - my-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: lord139055
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
